name: Continuous Live Winner Alerts

on:
  schedule:
    # Trigger 1 [ALL DAY MARKETS]: Runs continuously from 12:45 PM IST to 6:00 PM IST (07:15 AM UTC)
    - cron: '15 07 * * 1-5'
    
    # Trigger 2 [ALL NIGHT MARKETS]: Runs continuously from 8:45 PM IST to 12:30 AM IST (03:15 PM UTC)
    - cron: '15 15 * * 1-5'

  workflow_dispatch: 

jobs:
  monitor-live-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: pip3 install requests beautifulsoup4 pytz

      - name: Execute Live Realtime Scraper Loop
        env:
          BOT_TOKEN: ${{ secrets.MY_SECRET_BOT_KEY }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python3 live_alerts.py

          # Section from inside live_alerts.yml
      - name: Save Log State
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add accuracy_history.csv last_live_msg_id.txt || true
          git commit -m "Log metrics update [skip ci]" || true
          git push || true
