name: Run Live Kalyan Open Tracker Loop

on:
  schedule:
    - cron: '15 7 * * 1-5'
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pip3 install requests beautifulsoup4 pytz
      - name: Run Engine
        env:
          BOT_TOKEN: ${{ secrets.MY_SECRET_BOT_KEY }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python3 simple_predict.py
      - name: Save Tracking State
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add last_msg_id.txt || true
          git commit -m "Update state [skip ci]" || true
          git push || true
